version: '3.8'

services:
  app-redis:
    image: redis/redis-stack:latest
    container_name: app-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    networks:
      - backend-network

  app:
    image: jackredd/student:1.0
    container_name: app-student
    depends_on:
      - app-redis
    ports:
      - "9090:9090"
      - "5005:5005"
    restart: always
    environment:
      - SPRING_CONFIG_LOCATION=https://raw.githubusercontent.com/Evgen-Krasnenkov/redismultithreading/master/src/main/resources/application.yaml
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge