version: '1.0'

services:
  app-redis:
    image: redis/redis-stack:latest
    container_name: app-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  app:
    build: '.'
    depends_on:
      - app-redis
    ports:
      - "9090:9090"