mock-endpoint:
  address: "demo6308572.mockable.io/student/address"
  account: demo6308572.mockable.io/student/account
  grades: demo6308572.mockable.io/student/grades

spring:
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 9090
